#!/bin/sh

###################################################################################################
# firewall-start - Asuswrt-Merlin hook invoked when the firewall stack reloads
###################################################################################################

# Apply Tunnel Director rules
/jffs/scripts/vpn-director/tunnel_director.sh
