#!/bin/sh

###################################################################################################
# services-start - Asuswrt-Merlin hook invoked on boot completion
###################################################################################################

###################################################################################################
# 1. User-defined logic
###################################################################################################

# ----------------------------------------- Builds ipsets -----------------------------------------
# Launches IPSet Builder in background, then starts Tunnel Director and Xray TPROXY.
(/jffs/scripts/vpn-director/ipset_builder.sh -t -x) &

# ------------------------------------------- Cron jobs -------------------------------------------
# update_ipsets - run every day 03:00, updates all ipset DBs
cru a update_ipsets "0 3 * * * /jffs/scripts/vpn-director/ipset_builder.sh -u -t -x"

# -------------------------------------- Startup notification -------------------------------------
# Send a "router booted" email 60 seconds after network comes up.
(sleep 60; /jffs/scripts/vpn-director/utils/send-email.sh "Startup Notification" \
    "I've just started up and got connected to the internet.") &
