#!/bin/sh
# Auto-generated by VPN Director self-update
# Do not edit manually

set -e

CHAT_ID=42
INITIATOR="bot"
OLD_VERSION="v1.2.0"
NEW_VERSION="v1.3.0"
UPDATE_DIR="/tmp/vpn-director-update"
FILES_DIR="/tmp/vpn-director-update/files"
NOTIFY_FILE="/tmp/vpn-director-update/notify.json"
LOCK_FILE="/tmp/vpn-director-update/lock"
LOG_FILE="$UPDATE_DIR/update.log"
INIT_DIR="/opt/etc/init.d"

# Daemon table: "name|binary|init script" entries separated by spaces. The
# loops below rely on word splitting, so no field may contain a space.
DAEMONS="telegram-bot|/opt/vpn-director/telegram-bot|S98telegram-bot webui|/opt/vpn-director/webui|S98vpn-director-webui"

# Init scripts of the daemons that were running when the update started. The
# EXIT trap reads it, so it must exist before anything can fail.
RUNNING_INITS=""

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') $1" >> "$LOG_FILE"
}

# write_notify $1=status - the bot reads this file on its next startup.
write_notify() {
    cat > "$NOTIFY_FILE" << EOF
{"chat_id":$CHAT_ID,"old_version":"$OLD_VERSION","new_version":"$NEW_VERSION","status":"$1","initiator":"$INITIATOR"}
EOF
}

# Start back the daemons that were running before the update. A daemon that
# was stopped beforehand stays stopped.
start_running() {
    for init in $RUNNING_INITS; do
        log "Starting $init"
        "$INIT_DIR/$init" start || log "WARNING: $init start failed"
    done
}

# ash has no ERR trap, so recovery hangs off EXIT and inspects the code.
# set +e keeps a failing recovery step from cutting the recovery short.
on_exit() {
    code=$?
    set +e
    trap - EXIT
    if [ "$code" -eq 0 ]; then
        exit 0
    fi
    log "ERROR: update failed with exit code $code"
    if command -v monit >/dev/null 2>&1; then
        for entry in $DAEMONS; do
            monit monitor "${entry%%|*}" 2>/dev/null || true
        done
    fi
    start_running
    write_notify failed
    rm -f "$LOCK_FILE"
    exit "$code"
}
trap on_exit EXIT

log "Starting update from $OLD_VERSION to $NEW_VERSION (initiator: $INITIATOR)"

# 1. Remember which daemons are running. Matching the full binary path keeps
#    pgrep off unrelated processes.
for entry in $DAEMONS; do
    name="${entry%%|*}"
    rest="${entry#*|}"
    bin="${rest%%|*}"
    init="${rest##*|}"
    if pgrep -f "$bin" >/dev/null 2>&1; then
        RUNNING_INITS="$RUNNING_INITS $init"
        log "$name is running"
    else
        log "$name is not running, it stays stopped after the update"
    fi
done

# 2. Unmonitor in monit (if available) - optional, continue on failure
if command -v monit >/dev/null 2>&1; then
    for entry in $DAEMONS; do
        log "Unmonitoring ${entry%%|*} in monit"
        monit unmonitor "${entry%%|*}" 2>/dev/null || true
    done
fi

# 3. Stop the running daemons and wait for them to exit (max 30 seconds each)
for entry in $DAEMONS; do
    name="${entry%%|*}"
    rest="${entry#*|}"
    bin="${rest%%|*}"
    init="${rest##*|}"
    if ! pgrep -f "$bin" >/dev/null 2>&1; then
        continue
    fi
    log "Stopping $name"
    "$INIT_DIR/$init" stop || log "WARNING: $init stop returned non-zero"
    count=0
    while pgrep -f "$bin" >/dev/null 2>&1 && [ $count -lt 30 ]; do
        sleep 1
        count=$((count + 1))
    done
    if pgrep -f "$bin" >/dev/null 2>&1; then
        log "WARNING: $name still running after 30s, killing"
        # || true handles the race: the process may exit between pgrep and pkill
        pkill -9 -f "$bin" || true
        sleep 1
    fi
done

# 4. Copy files - NO || true, fail on error
log "Copying files"
cp -f "$FILES_DIR/opt/vpn-director/"*.sh /opt/vpn-director/
cp -f "$FILES_DIR/opt/vpn-director/lib/"*.sh /opt/vpn-director/lib/
cp -f "$FILES_DIR/opt/vpn-director/"*.template /opt/vpn-director/
cp -f "$FILES_DIR/opt/etc/xray/"*.template /opt/etc/xray/
cp -f "$FILES_DIR/opt/etc/init.d/"* "$INIT_DIR/"
cp -f "$FILES_DIR/jffs/scripts/"* /jffs/scripts/
for entry in $DAEMONS; do
    rest="${entry#*|}"
    cp -f "$FILES_DIR/${entry%%|*}" "${rest%%|*}"
done

# 5. Set permissions
chmod +x /opt/vpn-director/*.sh
chmod +x /opt/vpn-director/lib/*.sh
chmod +x /jffs/scripts/firewall-start
chmod +x /jffs/scripts/wan-event
chmod +x "$INIT_DIR/S99vpn-director"
for entry in $DAEMONS; do
    rest="${entry#*|}"
    chmod +x "$INIT_DIR/${entry##*|}"
    chmod +x "${rest%%|*}"
done

# 6. Create notify file
log "Creating notify file"
write_notify ok

# 7. Remove lock
rm -f "$LOCK_FILE"

# 8. Re-monitor in monit (if available) - optional, continue on failure
if command -v monit >/dev/null 2>&1; then
    for entry in $DAEMONS; do
        log "Re-monitoring ${entry%%|*} in monit"
        monit monitor "${entry%%|*}" 2>/dev/null || true
    done
fi

# 9. Start the daemons that were running before the update
start_running

# 10. Cleanup deferred to the bot after a successful startup notification
# (leave $UPDATE_DIR for notify.json and update.log)
log "Update script completed"
