#!/bin/bash
echo "ipset $*" >> /tmp/bats_ipset_calls.log
case "$1" in
    list)
        case "$2" in
            -n) echo "$3" ;;  # just echo the name back
            ru|us|ca)
                echo "Name: $2"
                echo "Type: hash:net"
                echo "Number of entries: 1000"
                ;;
            XRAY_CLIENTS|XRAY_SERVERS)
                echo "Name: $2"
                echo "Type: hash:net"
                echo "Number of entries: 5"
                ;;
            *) exit 1 ;;  # ipset doesn't exist
        esac
        ;;
    create|add|flush|destroy|save|restore) exit 0 ;;
    *) exit 0 ;;
esac
